openapi: 3.0.0
info:
  title: WoE Service
  description: A service to support the Where On Earth game
  version: 1.0.0
servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: The Where On Earth game service
paths:
  /repairs:
    get:
      operationId: listRepairs
      summary: List all repairs
      description: Returns a list of repairs with their details and images
      parameters:
        - name: assignedTo
          in: query
          description: Filter repairs by who they're assigned to
          schema:
            type: string
          required: false
      responses:
        '200':
          description: A list of repairs
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the repair
                        title:
                          type: string
                          description: The short summary of the repair
                        description:
                          type: string
                          description: The detailed description of the repair
                        assignedTo:
                          type: string
                          description: The user who is responsible for the repair
                        date:
                          type: string
                          format: date-time
                          description: The date and time when the repair is scheduled or completed
                        image:
                          type: string
                          format: uri
                          description: The URL of the image of the item to be repaired or the repair process

  /checkStatus:
    get:
      operationId: checkStatus
      summary: Check status of the game
      description: Returns the current status of the game
      responses:
        '200':
          description: The current status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current status of the game
  /startGame:
    get:
      operationId: startGame
      summary: Starts the game
      description: Triggers the start of the daily game
      responses:
        '200':
          description: The current status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current status of the game
  /findImage:
    get:
      operationId: findImage
      summary: Find an image to be used for the game
      description: Returns a suggested image for the daily game
      responses:
        '200':
          description: The current status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current status of the game
  /selectImage:
    get:
      operationId: selectImage
      summary: Select the current image to be used for the daily game
      description: Chooses the current image and moves to the guessing phase
      responses:
        '200':
          description: The current status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current status of the game