openapi: 3.0.0
info:
  title: WoE Service
  description: A service to support the Where On Earth game
  version: 1.0.0
servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: The Where On Earth game service
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth configuration for the repair service
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/${{AAD_APP_TENANT_ID}}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/${{AAD_APP_TENANT_ID}}/oauth2/v2.0/token
          scopes:
            api://${{AAD_APP_CLIENT_ID}}/check_status: Check status
paths:
  /checkStatus:
    get:
      operationId: checkStatus
      summary: Check status of the game
      description: Returns the current status of the game
      security:
            - oAuth2AuthCode: []
      responses:
        '200':
          description: The current status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current statis of the game